### ISSUE TITLE
Presentación

### ISSUE THREAD

**Issue by reginagarciah** [reginagarciah/parcial3-#4]
- Presentación  en latex usando beamer (subir .tex y .pdf)

**Comment by laumtz21** [comment]
[Proyecto final presentación.pdf](https://github.com/reginagarciah/parcial3-/files/7610060/Proyecto.final.presentacion.pdf)
Zip donde se encuentra el archivo txt: [Presentación txt.zip](https://github.com/reginagarciah/parcial3-/files/7610072/Presentacion.txt.zip)
